//! Real-shell tests for the TAB-completion interception hooks generated by
//! `src/shell_integration.rs` (`completion_hook_zsh` / `completion_hook_fish`).
//! Each test drives a real interactive shell over a PTY: type a partial word,
//! press TAB, and assert the `OSC 1337;Completions=` sequence arrives with the
//! expected word and candidates (RS/US framing). The zsh case also round-trips
//! the FRONTEND insertion contract (DEL × word-length + replacement) and
//! verifies the line editor lands on exactly the replaced word.
//!
//! The zsh test needs the completion system active, so its temp HOME ships a
//! `.zshrc` that loads compinit — mirroring the common real-user setup the
//! hook must survive. The fish test runs with TERM=dumb: fish 4.x probes the
//! terminal at startup (DA1, OSC 11, XTVERSION…) and blocks input until the
//! queries resolve; a bare test PTY answers none of them, while the real app's
//! xterm.js does — dumb skips the whole negotiation. Tests self-skip when the
//! shell is not installed.

use lumina_terminal_lib::shell_integration::{completion_hook_fish, completion_hook_zsh};
use portable_pty::{CommandBuilder, NativePtySystem, PtySize, PtySystem};
use std::io::{Read, Write};
use std::sync::mpsc;
use std::time::{Duration, Instant};

const OSC_PREFIX: &str = "\x1b]1337;Completions=";
const RS: char = '\x1e';
const US: char = '\x1f';

/// Temp dir helper: unique per test, auto-cleaned on drop.
struct TempDir(std::path::PathBuf);

impl TempDir {
    fn new(tag: &str) -> Self {
        let dir = std::env::temp_dir().join(format!(
            "lumina-completion-{}-{}-{}",
            tag,
            std::process::id(),
            Instant::now().elapsed().as_nanos()
        ));
        std::fs::create_dir_all(&dir).expect("create temp dir");
        Self(dir)
    }

    fn path(&self) -> &std::path::Path {
        &self.0
    }
}

impl Drop for TempDir {
    fn drop(&mut self) {
        let _ = std::fs::remove_dir_all(&self.0);
    }
}

fn shell_runs(shell: &str) -> bool {
    std::process::Command::new(shell)
        .arg("--version")
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .status()
        .map(|s| s.success())
        .unwrap_or(false)
}

/// A live interactive shell on its own PTY. Bytes written go to the shell as
/// keystrokes; `read_until` collects output until a marker shows up.
struct PtyShell {
    writer: Box<dyn Write + Send>,
    rx: mpsc::Receiver<u8>,
}

impl PtyShell {
    fn spawn(cmd: CommandBuilder) -> Self {
        let pty_system = NativePtySystem {};
        let pair = pty_system
            .openpty(PtySize {
                rows: 24,
                cols: 80,
                pixel_width: 0,
                pixel_height: 0,
            })
            .expect("openpty");
        let _child = pair.slave.spawn_command(cmd).expect("spawn shell");
        // The child holds its own dup of the slave fd, so the parent-side
        // handles can go away once we've taken the reader/writer clones.

        let mut reader = pair.master.try_clone_reader().expect("clone reader");
        let (tx, rx) = mpsc::channel::<u8>();
        std::thread::spawn(move || {
            let mut buf = [0u8; 4096];
            loop {
                match reader.read(&mut buf) {
                    Ok(0) | Err(_) => break,
                    Ok(n) => {
                        for &b in &buf[..n] {
                            if tx.send(b).is_err() {
                                return;
                            }
                        }
                    }
                }
            }
        });
        let writer = pair.master.take_writer().expect("take writer");
        drop(pair);
        Self { writer, rx }
    }

    /// Wait until the stream goes quiet for `settle` — the shell is at its
    /// prompt. Returns everything captured so far.
    fn wait_prompt(&self, settle: Duration, overall: Duration) -> String {
        let mut out = Vec::new();
        let deadline = Instant::now() + overall;
        loop {
            match self.rx.recv_timeout(settle) {
                Ok(b) => out.push(b),
                Err(mpsc::RecvTimeoutError::Timeout) => {
                    return String::from_utf8_lossy(&out).into_owned()
                }
                Err(mpsc::RecvTimeoutError::Disconnected) => {
                    return String::from_utf8_lossy(&out).into_owned()
                }
            }
            if Instant::now() > deadline {
                return String::from_utf8_lossy(&out).into_owned();
            }
        }
    }

    /// Accumulate output until it contains `marker` (returning the whole
    /// capture) or `timeout` passes (returning None).
    fn read_until(&self, marker: &str, timeout: Duration) -> Option<String> {
        let mut out = Vec::new();
        let bytes = marker.as_bytes();
        let deadline = Instant::now() + timeout;
        loop {
            let remaining = deadline.saturating_duration_since(Instant::now());
            if remaining.is_zero() {
                return None;
            }
            match self.rx.recv_timeout(remaining.min(Duration::from_millis(50))) {
                Ok(b) => {
                    out.push(b);
                    if contains_subslice(&out, bytes) {
                        return Some(String::from_utf8_lossy(&out).into_owned());
                    }
                }
                Err(mpsc::RecvTimeoutError::Timeout) => continue,
                Err(mpsc::RecvTimeoutError::Disconnected) => {
                    return if contains_subslice(&out, bytes) {
                        Some(String::from_utf8_lossy(&out).into_owned())
                    } else {
                        None
                    };
                }
            }
        }
    }

    /// Read one full `OSC 1337;Completions=…BEL` sequence: first the prefix,
    /// then the BEL terminator, returning the payload between them.
    fn read_completion_osc(&self, timeout: Duration) -> Option<String> {
        let out = self.read_until(OSC_PREFIX, timeout)?;
        let rest = self.read_until("\x07", timeout)?;
        // The capture may end mid-prefix (payload starts in the next chunk) or
        // already carry the start of the payload; either way take everything
        // between the prefix and the first BEL.
        let head = out.split(OSC_PREFIX).nth(1).unwrap_or("").split('\x07').next().unwrap_or("");
        let tail = rest.split('\x07').next().unwrap_or("");
        Some(format!("{head}{tail}"))
    }

    fn send(&mut self, data: &str) {
        self.writer.write_all(data.as_bytes()).expect("write to pty");
        self.writer.flush().expect("flush pty");
    }
}

fn contains_subslice(haystack: &[u8], needle: &[u8]) -> bool {
    needle.is_empty() || haystack.windows(needle.len()).any(|w| w == needle)
}

/// Split a Completions payload into ((ctx, word), [(insert, label, desc), …]).
/// The head record is `context US word` — the line context (tokens before the
/// word, the frontend warm-cache key; empty at command position).
fn parse_payload(payload: &str) -> ((String, String), Vec<(String, String, String)>) {
    let mut records = payload.split(RS);
    let mut head = records.next().unwrap_or("").split(US);
    let ctx = head.next().unwrap_or("").to_string();
    let word = head.next().unwrap_or("").to_string();
    let cands = records
        .filter_map(|r| {
            let mut fields = r.split(US);
            let insert = fields.next()?.to_string();
            Some((
                insert,
                fields.next().unwrap_or("").to_string(),
                fields.next().unwrap_or("").to_string(),
            ))
        })
        .collect();
    ((ctx, word), cands)
}

fn spawn_zsh(home: &TempDir, zdot: &TempDir, cwd: Option<&TempDir>) -> PtyShell {
    std::fs::write(
        home.path().join(".zshrc"),
        "autoload -Uz compinit\ncompinit -u\n",
    )
    .expect("write user zshrc");
    std::fs::write(
        zdot.path().join(".zshrc"),
        format!(
            "[ -r \"$HOME/.zshrc\" ] && source \"$HOME/.zshrc\"\n{}",
            completion_hook_zsh()
        ),
    )
    .expect("write lumina zshrc");
    let mut cmd = CommandBuilder::new("zsh");
    cmd.env("HOME", home.path().to_string_lossy().into_owned());
    cmd.env("ZDOTDIR", zdot.path().to_string_lossy().into_owned());
    // zle needs a real terminal type — cargo-test environments may run with
    // TERM unset/dumb, where zsh refuses to enable the line editor at all.
    cmd.env("TERM", "xterm-256color");
    cmd.env_remove("ZSH_ENV");
    if let Some(dir) = cwd {
        cmd.cwd(dir.path().to_string_lossy().into_owned());
    }
    cmd.args(["-i"]);
    PtyShell::spawn(cmd)
}

#[test]
fn zsh_hook_emits_completions_and_round_trips_insertion() {
    if !shell_runs("zsh") {
        eprintln!("skipping zsh completion test: zsh not available");
        return;
    }
    let home = TempDir::new("zsh-home");
    let zdot = TempDir::new("zsh-zdot");
    let mut shell = spawn_zsh(&home, &zdot, None);

    shell.wait_prompt(Duration::from_millis(700), Duration::from_secs(10));

    // Command-name completion: "ech" + TAB must arrive as an OSC carrying the
    // word and the "echo" candidate.
    shell.send("ech\t");
    let payload = shell
        .read_completion_osc(Duration::from_secs(8))
        .unwrap_or_else(|| panic!("zsh completion OSC did not arrive after TAB"));
    let ((ctx, word), cands) = parse_payload(&payload);
    assert_eq!(word, "ech", "word must be the typed token; payload: {payload:?}");
    assert_eq!(ctx, "", "command position has an empty context; payload: {payload:?}");
    assert!(
        cands.iter().any(|(insert, _, _)| insert == "echo"),
        "echo candidate missing; payload: {payload:?}"
    );

    // Frontend insertion contract: DEL × len("ech") + replacement, then run it.
    // "ech" erased, "printf zsh-hook-ok" typed, Enter → the shell echoes the
    // command and runs it. Asserts the DEL count matches the word length.
    shell.wait_prompt(Duration::from_millis(400), Duration::from_secs(5));
    shell.send("\x7f\x7f\x7fprintf zsh-hook-ok\r");
    // zle erases with backspace-redraw sequences, so the echoed command has no
    // \r right after it — match the bare text and check the full line below.
    let out = shell
        .read_until("zsh-hook-ok", Duration::from_secs(8))
        .expect("inserted line echoed back");
    // The echoed command line proves three DELs removed exactly "ech": the
    // line starts at "printf", and printf's own output follows.
    assert!(
        out.contains("printf zsh-hook-ok"),
        "line after insertion must be exactly 'printf zsh-hook-ok'"
    );
}

#[test]
fn zsh_hook_completes_files() {
    if !shell_runs("zsh") {
        eprintln!("skipping zsh file-completion test: zsh not available");
        return;
    }
    let home = TempDir::new("zshf-home");
    let zdot = TempDir::new("zshf-zdot");
    let cwd = TempDir::new("zshf-cwd");
    std::fs::write(cwd.path().join("lumina_probe_one.txt"), b"x").unwrap();
    std::fs::write(cwd.path().join("lumina_probe_two.txt"), b"x").unwrap();

    let mut shell = spawn_zsh(&home, &zdot, Some(&cwd));
    shell.wait_prompt(Duration::from_millis(700), Duration::from_secs(10));
    shell.send("./lumina_probe_\t");
    let payload = shell
        .read_completion_osc(Duration::from_secs(8))
        .unwrap_or_else(|| panic!("zsh file completion OSC did not arrive"));
    let ((_ctx, word), cands) = parse_payload(&payload);
    assert_eq!(word, "./lumina_probe_", "word must be the typed token; payload: {payload:?}");
    let inserts: Vec<&str> = cands.iter().map(|(i, _, _)| i.as_str()).collect();
    assert!(
        inserts.iter().any(|i| i.ends_with("lumina_probe_one.txt"))
            && inserts.iter().any(|i| i.ends_with("lumina_probe_two.txt")),
        "file candidates missing; got {inserts:?}"
    );
}

#[test]
fn zsh_hook_escapes_path_candidates_with_spaces() {
    if !shell_runs("zsh") {
        eprintln!("skipping zsh spaces completion test: zsh not available");
        return;
    }
    let home = TempDir::new("zshsp-home");
    let zdot = TempDir::new("zshsp-zdot");
    let cwd = TempDir::new("zshsp-cwd");
    std::fs::create_dir(cwd.path().join("My Target")).unwrap();
    std::fs::write(cwd.path().join("My Notes.txt"), b"x").unwrap();

    let mut shell = spawn_zsh(&home, &zdot, Some(&cwd));
    shell.wait_prompt(Duration::from_millis(700), Duration::from_secs(10));

    // Plain prefix: compsys has two compadd caller kinds for the same word —
    // raw (e.g. _cd's listing, which the real compadd would quote at INSERT
    // time) and pre-escaped -Q (_path_files). Both must arrive as the ESCAPED
    // form; a raw candidate replayed as keystrokes would split the argument.
    shell.send("cd My\t");
    let payload = shell
        .read_completion_osc(Duration::from_secs(8))
        .unwrap_or_else(|| panic!("zsh completion OSC did not arrive"));
    let ((_ctx, word), cands) = parse_payload(&payload);
    assert_eq!(word, "My", "word must be the typed token; payload: {payload:?}");
    let inserts: Vec<&str> = cands.iter().map(|(i, _, _)| i.as_str()).collect();
    assert!(
        inserts.contains(&"My\\ Target"),
        "escaped dir candidate missing; got {inserts:?}"
    );
    assert!(
        !inserts.contains(&"My Target"),
        "the raw twin (escaped-space form deduped away) must not be offered; got {inserts:?}"
    );

    // Already-escaped input (the user typed `\ ` themselves) keeps matching
    // and stays escaped.
    shell.wait_prompt(Duration::from_millis(400), Duration::from_secs(5));
    shell.send("\x15cd My\\ Ta\t");
    let payload = shell
        .read_completion_osc(Duration::from_secs(8))
        .unwrap_or_else(|| panic!("zsh escaped-input OSC did not arrive"));
    let ((_ctx, word), cands) = parse_payload(&payload);
    assert_eq!(word, "My\\ Ta", "word is the raw line-editor token; payload: {payload:?}");
    assert!(
        cands.iter().any(|(i, _, _)| i == "My\\ Target"),
        "escaped candidate missing for escaped input; payload: {payload:?}"
    );

    // Frontend insertion contract on the escaped candidate: DEL × 6 erases
    // "My\ Ta", the escaped insert types one shell word, and cd actually
    // lands inside the directory — pwd proves the space survived as one
    // argument (the echoed `cd My\ Target` never contains a bare "My Target",
    // so the marker can only come from the pwd output).
    shell.wait_prompt(Duration::from_millis(400), Duration::from_secs(5));
    shell.send("\x7f\x7f\x7f\x7f\x7f\x7fMy\\ Target\r");
    shell.wait_prompt(Duration::from_millis(400), Duration::from_secs(5));
    shell.send("pwd\r");
    let out = shell
        .read_until("My Target", Duration::from_secs(8))
        .expect("pwd must report the spaced directory");
    assert!(
        !out.contains("no such file or directory"),
        "cd must not fail; got: {out:?}"
    );
}

#[test]
fn fish_hook_escapes_path_candidates_with_spaces() {
    if !shell_runs("fish") {
        eprintln!("skipping fish spaces completion test: fish not available");
        return;
    }
    let home = TempDir::new("fishsp-home");
    let cwd = TempDir::new("fishsp-cwd");
    std::fs::create_dir(cwd.path().join("My Target")).unwrap();

    let mut cmd = CommandBuilder::new("fish");
    cmd.env("HOME", home.path().to_string_lossy().into_owned());
    // dumb skips fish's startup terminal negotiation (DA1/OSC11/XTVERSION),
    // which a bare test PTY never answers — see the module comment.
    cmd.env("TERM", "dumb");
    cmd.cwd(cwd.path().to_string_lossy().into_owned());
    cmd.args(["--login", "-i", "-C", &completion_hook_fish()]);
    let mut shell = PtyShell::spawn(cmd);

    shell.wait_prompt(Duration::from_millis(900), Duration::from_secs(10));

    // complete -C reports raw tokens; the hook must ship the insert text
    // backslash-escaped (fish's own accept form) while the label keeps the
    // raw text for display.
    shell.send("cd My\t");
    let payload = shell
        .read_completion_osc(Duration::from_secs(8))
        .unwrap_or_else(|| panic!("fish completion OSC did not arrive"));
    let ((_ctx, word), cands) = parse_payload(&payload);
    assert_eq!(word, "My", "word must be the typed token; payload: {payload:?}");
    let target = cands
        .iter()
        .find(|(i, _, _)| i == "My\\ Target/")
        .unwrap_or_else(|| panic!("escaped dir candidate missing; payload: {payload:?}"));
    assert_eq!(target.1, "My Target/", "label keeps the raw text for display");
    assert!(
        !cands.iter().any(|(i, _, _)| i == "My Target/"),
        "the raw unescaped form must not be offered; payload: {payload:?}"
    );

    // Escaped input: the word is the raw line-editor token (`My\ Ta`) and the
    // candidate stays escaped; the frontend contract (DEL × 6 + insert) must
    // erase the user's `\ ` and retype a correctly quoted single word.
    shell.wait_prompt(Duration::from_millis(500), Duration::from_secs(5));
    shell.send("\x15cd My\\ Ta\t");
    let payload = shell
        .read_completion_osc(Duration::from_secs(8))
        .unwrap_or_else(|| panic!("fish escaped-input OSC did not arrive"));
    let ((_ctx, word), cands) = parse_payload(&payload);
    assert_eq!(word, "My\\ Ta", "word must be the raw typed token; payload: {payload:?}");
    assert!(
        cands.iter().any(|(i, _, _)| i == "My\\ Target/"),
        "escaped candidate missing; payload: {payload:?}"
    );

    shell.wait_prompt(Duration::from_millis(500), Duration::from_secs(5));
    shell.send("\x7f\x7f\x7f\x7f\x7f\x7fMy\\ Target/\r");
    shell.wait_prompt(Duration::from_millis(500), Duration::from_secs(5));
    shell.send("pwd\r");
    let out = shell
        .read_until("My Target", Duration::from_secs(8))
        .expect("pwd must report the spaced directory");
    assert!(
        !out.contains("cd: The directory") && !out.contains("No such directory"),
        "cd must not fail; got: {out:?}"
    );
}

#[test]
fn zsh_hook_labels_show_last_path_component() {
    if !shell_runs("zsh") {
        eprintln!("skipping zsh label test: zsh not available");
        return;
    }
    let home = TempDir::new("zshlb-home");
    let zdot = TempDir::new("zshlb-zdot");
    let cwd = TempDir::new("zshlb-cwd");
    std::fs::create_dir_all(cwd.path().join("proj a/src x/inner")).unwrap();
    std::fs::write(cwd.path().join("proj a/src x/notes.txt"), b"x").unwrap();

    let mut shell = spawn_zsh(&home, &zdot, Some(&cwd));
    shell.wait_prompt(Duration::from_millis(700), Duration::from_secs(10));

    // Nested path with spaces: the insert must stay the full escaped path
    // (accepting replaces the whole word), but the label shown in the popup
    // is only the last component — the typed line already carries the prefix,
    // and full paths overflow the row.
    shell.send("cat proj\\ a/src\\ x/n\t");
    let payload = shell
        .read_completion_osc(Duration::from_secs(8))
        .unwrap_or_else(|| panic!("zsh completion OSC did not arrive"));
    let ((_ctx, word), cands) = parse_payload(&payload);
    assert_eq!(
        word, "proj\\ a/src\\ x/n",
        "word is the raw line-editor token; payload: {payload:?}"
    );
    let cand = cands
        .iter()
        .find(|(i, _, _)| i == "proj\\ a/src\\ x/notes.txt")
        .unwrap_or_else(|| panic!("full escaped insert missing; payload: {payload:?}"));
    assert_eq!(cand.1, "notes.txt", "label must be the last path component");
}

#[test]
fn fish_hook_labels_show_last_path_component() {
    if !shell_runs("fish") {
        eprintln!("skipping fish label test: fish not available");
        return;
    }
    let home = TempDir::new("fishlb-home");
    let cwd = TempDir::new("fishlb-cwd");
    std::fs::create_dir_all(cwd.path().join("proj a/src x/inner")).unwrap();
    std::fs::write(cwd.path().join("proj a/src x/notes.txt"), b"x").unwrap();

    let mut cmd = CommandBuilder::new("fish");
    cmd.env("HOME", home.path().to_string_lossy().into_owned());
    cmd.env("TERM", "dumb");
    cmd.cwd(cwd.path().to_string_lossy().into_owned());
    cmd.args(["--login", "-i", "-C", &completion_hook_fish()]);
    let mut shell = PtyShell::spawn(cmd);

    shell.wait_prompt(Duration::from_millis(900), Duration::from_secs(10));

    shell.send("cat proj\\ a/src\\ x/n\t");
    let payload = shell
        .read_completion_osc(Duration::from_secs(8))
        .unwrap_or_else(|| panic!("fish completion OSC did not arrive"));
    let ((_ctx, word), cands) = parse_payload(&payload);
    assert_eq!(
        word, "proj\\ a/src\\ x/n",
        "word must be the raw typed token; payload: {payload:?}"
    );
    let cand = cands
        .iter()
        .find(|(i, _, _)| i == "proj\\ a/src\\ x/notes.txt")
        .unwrap_or_else(|| panic!("full escaped insert missing; payload: {payload:?}"));
    assert_eq!(cand.1, "notes.txt", "label must be the last path component");
}

#[test]
fn fish_hook_emits_completions() {
    if !shell_runs("fish") {
        eprintln!("skipping fish completion test: fish not available");
        return;
    }
    let home = TempDir::new("fish-home");
    let cwd = TempDir::new("fish-cwd");
    std::fs::write(cwd.path().join("lumina_probe_one.txt"), b"x").unwrap();
    std::fs::write(cwd.path().join("lumina_probe_two.txt"), b"x").unwrap();

    let mut cmd = CommandBuilder::new("fish");
    cmd.env("HOME", home.path().to_string_lossy().into_owned());
    // dumb skips fish's startup terminal negotiation (DA1/OSC11/XTVERSION),
    // which a bare test PTY never answers — see the module comment.
    cmd.env("TERM", "dumb");
    cmd.cwd(cwd.path().to_string_lossy().into_owned());
    cmd.args(["--login", "-i", "-C", &completion_hook_fish()]);
    let mut shell = PtyShell::spawn(cmd);

    shell.wait_prompt(Duration::from_millis(900), Duration::from_secs(10));

    // Command completion with fish's description attached.
    shell.send("ech\t");
    let payload = shell
        .read_completion_osc(Duration::from_secs(8))
        .unwrap_or_else(|| panic!("fish completion OSC did not arrive after TAB"));
    let ((ctx, word), cands) = parse_payload(&payload);
    assert_eq!(word, "ech", "word must be the typed token; payload: {payload:?}");
    assert_eq!(ctx, "", "command position has an empty context; payload: {payload:?}");
    let echo = cands
        .iter()
        .find(|(insert, _, _)| insert == "echo")
        .unwrap_or_else(|| panic!("echo candidate missing; payload: {payload:?}"));
    assert!(!echo.2.is_empty(), "echo should carry fish's description");

    // Argument-position file completion. \x15 (kill-line) clears the echo.
    shell.wait_prompt(Duration::from_millis(500), Duration::from_secs(5));
    shell.send("\x15cat lumina_probe_\t");
    let payload = shell
        .read_completion_osc(Duration::from_secs(8))
        .unwrap_or_else(|| panic!("fish file completion OSC did not arrive"));
    let ((ctx, word), cands) = parse_payload(&payload);
    assert_eq!(word, "lumina_probe_", "word must be the typed token; payload: {payload:?}");
    assert_eq!(ctx, "cat", "argument position context is the preceding tokens; payload: {payload:?}");
    let inserts: Vec<&str> = cands.iter().map(|(i, _, _)| i.as_str()).collect();
    assert!(
        inserts.contains(&"lumina_probe_one.txt") && inserts.contains(&"lumina_probe_two.txt"),
        "file candidates missing; got {inserts:?}"
    );
}
