//! Real-shell lifecycle tests for the proxy-sync hooks generated by
//! `src/shell_integration.rs`: each hook runs inside an actual bash/zsh/fish
//! process through the full proxy-sync lifecycle — apply → no-op on unchanged
//! file → user manual override survives a proxy-off transition → re-apply with
//! a new value → unset only what the hook itself injected.

use lumina_terminal_lib::shell_integration::{proxy_hook_bash, proxy_hook_fish, proxy_hook_zsh};
use std::process::Command;

/// Unique temp dir for one test's env-file, so parallel tests don't clash.
fn temp_env_file(tag: &str) -> std::path::PathBuf {
    let dir = std::env::temp_dir().join(format!("lumina-proxy-hook-{}-{}", tag, std::process::id()));
    std::fs::create_dir_all(&dir).expect("create temp dir");
    dir.join("proxy.env")
}

fn shell_runs(name: &str) -> bool {
    Command::new(name)
        .arg("--version")
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false)
}

/// The proxy-sync lifecycle every hook must survive, in POSIX syntax
/// (bash/zsh). `{ENVF}` is substituted with the baked env-file path.
const POSIX_SCENARIO: &str = r#"
printf '%s\n' '# lumina proxy v1' 'http_proxy=http://127.0.0.1:7890' > "{ENVF}"
__lumina_proxy
[ "$http_proxy" = http://127.0.0.1:7890 ] || { echo FAIL1; exit 1; }
__lumina_proxy
[ "$http_proxy" = http://127.0.0.1:7890 ] || { echo FAIL2; exit 1; }
export https_proxy=http://manual:1
export http_proxy=http://user:1
printf '%s\n' '# lumina proxy v1' > "{ENVF}"
__lumina_proxy
[ "$http_proxy" = http://user:1 ] || { echo FAIL3; exit 1; }
[ "$https_proxy" = http://manual:1 ] || { echo FAIL4; exit 1; }
printf '%s\n' '# lumina proxy v1' 'http_proxy=http://127.0.0.2:7890' > "{ENVF}"
__lumina_proxy
[ "$http_proxy" = http://127.0.0.2:7890 ] || { echo FAIL5; exit 1; }
printf '%s\n' '# lumina proxy v1' > "{ENVF}"
__lumina_proxy
[ -z "${http_proxy-}" ] || { echo FAIL6; exit 1; }
echo HOOK-OK
"#;

/// The same scenario in fish syntax (no `export`/`[`, `or begin … end`).
const FISH_SCENARIO: &str = r#"
printf '%s\n' '# lumina proxy v1' 'http_proxy=http://127.0.0.1:7890' > "{ENVF}"
__lumina_proxy
test "$http_proxy" = http://127.0.0.1:7890; or begin; echo FAIL1; exit 1; end
__lumina_proxy
test "$http_proxy" = http://127.0.0.1:7890; or begin; echo FAIL2; exit 1; end
set -gx https_proxy http://manual:1
set -gx http_proxy http://user:1
printf '%s\n' '# lumina proxy v1' > "{ENVF}"
__lumina_proxy
test "$http_proxy" = http://user:1; or begin; echo FAIL3; exit 1; end
test "$https_proxy" = http://manual:1; or begin; echo FAIL4; exit 1; end
printf '%s\n' '# lumina proxy v1' 'http_proxy=http://127.0.0.2:7890' > "{ENVF}"
__lumina_proxy
test "$http_proxy" = http://127.0.0.2:7890; or begin; echo FAIL5; exit 1; end
printf '%s\n' '# lumina proxy v1' > "{ENVF}"
__lumina_proxy
test -z "$http_proxy"; or begin; echo FAIL6; exit 1; end
echo HOOK-OK
"#;

fn run_hook_scenario(shell: &str, hook: &str, scenario: &str, env_file: &std::path::Path) {
    if !shell_runs(shell) {
        eprintln!("skipping {shell} hook test: {shell} not available");
        return;
    }
    let script = format!("{hook}\n{}", scenario.replace("{ENVF}", &env_file.to_string_lossy()));
    let out = Command::new(shell)
        .args(["-c", &script])
        .env_remove("http_proxy")
        .env_remove("HTTP_PROXY")
        .env_remove("https_proxy")
        .output()
        .expect("spawn shell");
    let stdout = String::from_utf8_lossy(&out.stdout);
    let stderr = String::from_utf8_lossy(&out.stderr);
    assert!(
        stdout.trim() == "HOOK-OK",
        "{shell} hook scenario failed\nstdout: {stdout}\nstderr: {stderr}\nscript:\n{script}"
    );
}

#[test]
fn bash_hook_lifecycle() {
    let env_file = temp_env_file("bash");
    run_hook_scenario(
        "bash",
        &proxy_hook_bash(&env_file.to_string_lossy()),
        POSIX_SCENARIO,
        &env_file,
    );
}

#[test]
fn zsh_hook_lifecycle() {
    let env_file = temp_env_file("zsh");
    run_hook_scenario(
        "zsh",
        &proxy_hook_zsh(&env_file.to_string_lossy()),
        POSIX_SCENARIO,
        &env_file,
    );
}

#[test]
fn fish_hook_lifecycle() {
    let env_file = temp_env_file("fish");
    run_hook_scenario(
        "fish",
        &proxy_hook_fish(&env_file.to_string_lossy()),
        FISH_SCENARIO,
        &env_file,
    );
}
